name: Ghostlife
version: ${project.version}
main: ghostlife.ghostlife.Ghostlife
api-version: '1.15'
authors: [ghost_46]
description: LIFE pligin

commands:
  addCustomModel:
    description: カスタムモデルデータ追加
  ghostlifereload:
    description: コンフィグリロード
  adddamege:
    description: ダメージセット
  sellmmitem:
    description: MMアイテム売却
  backpack:
    description: バックパック

permissions:
  addCustomModel.set.op:
    default: op
  ghostlifereload.set.op:
    default: op
  adddamage.set.op:
    default: op