cooltime: 60
wikimessage: "&fさんが&a公式wikiリンク&fを載せました\n https://azisabaofficial.playing.wiki/d/Life%c0%b8%b3%e8%bb%aa"
mmitem:
  yukiti_ticket:
    itemdisplay: "&3一万円"
    sellprice: 10000
  itiyou_ticket:
    itemdisplay: "&3五千円"
    sellprice: 5000
  syurei_ticket:
    itemdisplay: "&3二千円"
    sellprice: 2000
  noguti_ticket:
    itemdisplay: "&3千円"
    sellprice: 1000
  kouka:
    itemdisplay: "&6&l硬貨"
    sellprice: 7
  cave_shard:
    itemdisplay: "&7洞窟の欠片"
    sellprice: 5
  kokuyouseki:
    itemdisplay: "&0&l黒曜石&f"
    sellprice: 10